export default {
  div1: {
    display: "flex",
    flex: 1,
    opacity: 0.9,
    backgroundColor: "white",
    textAlign: "center",
    position: "absolute",
    zIndex: 999,
    overflow: "auto",
    bottom: -70,
    left: "38%",
    flexDirection: "column",
    alignItems: "center",
    paddingTop: 15,
    paddingBottom: 15,
    paddingRight: 20,
    width: "30%",
    borderRadius: 10,
  },
  div2: {
    borderRadius: 5,
    marginTop: 10,
    boxShadow: "0px 0px 2px 0px grey",
  },
  color: { backgroundColor: "#42a5f5", color: "white", marginTop: 10 },
  div3: {
    textAlign: "center",
    height: "100vh",
    minWidth: "100vw",
  },
};
