export default {
  searchtext: {
    textAlign: "center",
    textDecoration: "none",
    color: "white",
    paddingTop: 15,
    paddingBottom: 15,
  },

  orderPlacementTittle: {
    // textAlign: "center",
  },
  divproperty: { display: "flex", marginBottom: 30 },
  likeoreder: {
    marginRight: 10,
    // display: "flex",
    // flex: 0.5,
  },
  icon: { fontSize: 25, cursor: "pointer", color: "#42a5f5" },

  KeyboardDatePickerStyle: {
    padding: 5,
    width: "100%",
    borderRadius: 5,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "gray",
    backgroundColor: "white",
    boxShadow: " 0 0 17px -5px #9E9E9E",
  },

  select: {
    marginTop: 3,
    width: "100%",
    // padding: 5,
    borderRadius: 5,
    cursor: "pointer",
    boxShadow: " 0 0 17px -5px #9E9E9E",
  },
  selectDateTime: {
    marginTop: 3,
    width: "100%",
    padding: 5,
    borderRadius: 5,
    cursor: "pointer",
    boxShadow: " 0 0 17px -5px #9E9E9E",
  },
  inputFieldStyle: {
    marginBottom: 8,
    display: "flex",
    flexDirection: "column",
  },
  nextButton: {
    textAlign: "center",
    marginTop: 30,
    marginBottom: 20,
    backgroundColor: "#42a5f5",
    padding: 5,
    color: "white",
    borderRadius: 5,
    color: "white",
    textTransform: "capitalize",
  },
  ordertext: {
    fontWeight: "500",
    color: "#707070",
    fontSize: 20,
    marginBottom: 0,
  },
  text: {
    fontWeight: "500",
    color: "#707070",
    fontSize: 20,
  },
  searchdiv: {
    width: "100%",
    backgroundColor: "#42a5f5",
    borderRadius: 4,
  },
  // modalheader: { backgroundColor: "#42a5f5", color: "white" },
  textdecoration: { textDecoration: "none" },
  mapdiv: {
    textAlign: "center",
    height: 200,
    width: 300,
  },
  flex3: { flex: 0.3 },
  flex5: { flex: 0.3 },
  flex7: { flex: 0.7 },
  anyTime: { float: "right" },
};
