export default {
  titleGrid: {
    marginTop: 30,
    marginBottom: 10,
    display: "flex",
    flexDirecton: "row",
    justifyContent: "space-between",
    marginLeft: 55,
  },
  icon: { fontSize: 25, cursor: "pointer", color: "#42a5f5" },

  pDeco: { textDecoration: "underline", color: "#707070" },

  divMarginB: { marginBottom: 10 },

  pValue: {
    marginBottom: 0,
    color: "#42a5f5",
    fontSize: 14,
    fontWeight: "600",
  },
  divValue: {
    borderWidth: 1,
    borderStyle: "solid",
    borderBottomColor: "#9f9f9f",
    borderTopColor: "transparent",
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
  },
  pProp: {
    marginBottom: 0,
    color: "#9f9f9f",
    fontSize: 14,
  },

  btnDelete: {
    cursor: "pointer",
    marginBottom: 10,
    backgroundColor: "#e50000",
    borderWidth: 0,
    padding: 5,
    paddingLeft: "15%",
    paddingRight: "15%",
    color: "white",
    borderRadius: 5,
    textTransform: "capitalize",
  },
  pEstimateCost: {
    marginBottom: 0,
    color: "#42a5f5",
    fontSize: 14,
    fontWeight: "600",
  },
  mainGrid: {
    padding: 15,
    boxShadow: " 0 0 17px -5px #9E9E9E",
    borderRadius: 10,
    borderLeftColor: "#42a5f5",
    borderLeftStyle: "solid",
    borderLeftWidth: 10,
    paddingBottom: 10,
    display: "flex",
    flexDirection: "row",
    textAlign: "center",
  },
  placeOrderGrid: {
    borderLeftColor: "#42a5f5",
    borderLeftStyle: "solid",
    borderLeftWidth: 10,
    marginTop: 30,
    display: "flex",
    flexDirection: "row",
    padding: 20,
    marginBottom: 20,
    borderRadius: 10,
    boxShadow: " 0 0 17px -5px #9E9E9E",
  },
  pEstimateCostValue: { color: "#42a5f5" },

  btnPlaceOrder: {
    backgroundColor: "#42a5f5",
    borderWidth: 0,
    padding: 5,
    paddingLeft: "15%",
    paddingRight: "15%",
    color: "white",
    borderRadius: 5,
    textTransform: "capitalize",
  },
  divAlignRight: {
    textAlign: "right",
  },

  divEstimatePosition: { position: "absolute", bottom: 0, right: 25 },
};
