export default {
  ordersplaced: {
    fontWeight: "bold",
    fontSize: 25,
    // color: "#707070",
    color: "#42a5f5",
    marginLeft: 20,
  },
  centertext: { color: "gray", marginBottom: 20 },
  texttitle: { color: "#42a5f5", fontSize: 20, fontWeight: "500" },
  textcatagory: { color: "#42a5f5", fontWeight: "600", paddingTop: 20 },
  textplacement: { color: "#42a5f5", fontWeight: "600" },
  orderplacedcontainer: {
    display: "flex",
    marginTop: 20,
    boxShadow: " 0 0 17px -5px #9E9E9E",
    backgroundColor: "white",
    marginBottom: 30,
    paddingLeft: 20,
    paddingRight: 20,
    borderRadius: 10,
    paddingTop: 20,
    paddingBottom: 20,
  },
  heading: {
    // color: "#42a5f5",
    color: "gray",
    fontWeight: "600",
    fontSize: 21,
    marginTop: 10,
    // textAlign: 'center'
  },
  iconGrid: {
    marginTop: 40,
    marginBottom: 10,
    textAlign: "center",
  },
  titleGrid: {
    marginBottom: 20,
    marginTop: 40,
    textAlign: "center",
  },
  placeorderdashboard: {
    backgroundColor: "#42a5f5",
    borderWidth: 0,
    padding: 15,
    paddingLeft: "10%",
    paddingRight: "10%",
    color: "white",
    borderRadius: 4,
  },
  buttonsGrid: {
    display: "flex",
    flexDirection: "row",
    backgroundColor: "white",
    margintTop: 30,
    marginBottom: 30,
    paddingLeft: 20,
    paddingRight: 20,
    boxShadow: " 0 0 17px -5px #9E9E9E",
    borderRadius: 10,
    paddingTop: 20,
    paddingBottom: 20,
  },

  Button: {
    cursor: "pointer",
    backgroundColor: "#42a5f5",
    padding: 10,
    color: "white",
    borderRadius: 5,
    height: "40px",
    marginTop: 20,
    width: "35%",
    textTransform: "capitalize",
  },
};
